<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.zs</groupId>
        <artifactId>zs-business</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>zs-business-service</artifactId>

    <dependencies>
        <dependency>
            <groupId>com.zs</groupId>
            <artifactId>zs-business-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.zs</groupId>
            <artifactId>zs-common-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.zs</groupId>
            <artifactId>zs-common-aop</artifactId>
        </dependency>
        <dependency>
            <groupId>com.zs</groupId>
            <artifactId>zs-common-mybatis</artifactId>
        </dependency>
        <dependency>
            <groupId>com.zs</groupId>
            <artifactId>zs-system-api</artifactId>
        </dependency>
    </dependencies>

</project>